### PR TITLE
fix pkg_resources api deprecated warning

### PR DESCRIPTION
**Pull request by zhuwenxing**
/kind improvement

### CODE REVIEW

**Comment by zhuwenxing** [comment]
got warnings when using pymilvus
```
.venv/lib/python3.12/site-packages/pymilvus/client/__init__.py:6
  /Users/zilliz/workspace/milvus_beir/.venv/lib/python3.12/site-packages/pymilvus/client/__init__.py:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import DistributionNotFound, get_distribution

```

this pr is to fix this warning

**Comment by djwessel** [comment]
@XuanYang-cn When do we plan for this to find it's way into 2.x? we have now had at least 3 releases of 2.5.x since this fix

**Pull request merged**
