### PR TITLE
Revert support default value

### PR DESCRIPTION
**Pull request by XuanYang-cn**
- Revert "Support Default Value (#1444)" This reverts commit 5a581ce6097f36b20687f5aeb988db82ac6212e9.

- Revert "Fix default value appear when not set (#1451)" This reverts commit 69d9b409dd8ee3a0d1227145efc38015c97a4607.

- Revert "Fix default value store in unknow dataType (#1462)" This reverts commit cf81b472d7b0307d644f49b4772f64b58c1bf974.

- Revert "Make default value set None valid (#1473)" This reverts commit 72bec7c94446761ab4de4e57d1952b21d59cbfe6.

### CODE REVIEW

**Review by longjiquan — APPROVED** [review]
/lgtm

**Comment by XuanYang-cn** [comment]
image
/unhold

**Pull request merged**
