### PR TITLE
Disable logger from polluting other modules

### PR DESCRIPTION
**Pull request by ponponon**
https://github.com/milvus-io/pymilvus/pull/1631

The previous PR was unsigned and it was a bit of a hassle to re-sign it, so I just re-submitted the PR

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
image
@ponponon Could you please change the commit message to English with `git commit --amend` and rebase the latest codes to pass the Code checker actions

**Comment by ponponon** [comment]
> image @ponponon Could you please change the commit message to English with `git commit --amend` and rebase the latest codes to pass the Code checker actions

Has been changed to English

**Comment by ponponon** [comment]
> /lgtm /approve

With this fix, I hope to be able to release a 2.2.16 to solve the 2.2.x user's nuisance

**Pull request merged**
