### PR TITLE
Added grpc as a valid protocol for uri

### PR DESCRIPTION
**Pull request by brunocfnba**
Added grpc protocol to connection uri validation. Not having it was preventing grpc connections with the following error: <ConnectionConfigException: (code=1, message=Open local milvus failed, dir: grpc: is not exists)>

### CODE REVIEW

**Comment by XuanYang-cn** [comment]
@brunocfnba great work! 

To pass the code checker actions, please use `make format` to format the codes

**Comment by brunocfnba** [comment]
hey @XuanYang-cn it's my first PR here not sure if I follow. Where should I use `make format`. If you have any docs that might help. Thanks!

**Review by XuanYang-cn — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
